config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: %i[index show new create] do
    resource :posts, only: %i[new create]
  end

  resources :posts, only: %i[index show] do
    resources :comments, only: %i[index show new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts,    dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.find(params[:user_id])
  end

  def current_post
    Post.find(params[:post_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = current_post
    @comments = @post.comments.all
  end

  def show
    @post = current_post
    @comment = @post.comments.find(params[:id])
  end

  def new
    @post = current_post
    @comment = Comment.new
  end

  def create
    @post = current_post
    @comment = @post.comments.build(comment_params)
    @comment.user = @post.user
    if @comment.save
      redirect_to post_comment_path(@post, @comment)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.all.find(params[:id])
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.slim
h1= "#{ @post.title } Comments"

= link_to "Create new comment", new_post_comment_path(@post)

table.table.table-bordered
  thead
    tr
      th  Comment's Author
      th  Comment's Content
      th  Comment
  tbody
    - @comments.each do |comment|
      tr
        td = link_to comment.user.name, user_path(comment.user)
        td = comment.content
        td = link_to "Comment", post_comment_path(@post, comment)

app/views/comments/new.html.slim
= simple_form_for [@post, @comment] do |f|
  = f.input :content, label: 'Comment'
  = f.button :submit

app/views/comments/show.html.slim
table.table.table-bordered
  thead
    tr
      th  Comment's Author
      th  Comment's Content
  tbody
    tr
      td = link_to @comment.user.name, user_path(@comment.user)
      td = @comment.content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedRoutesDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.slim
h1= "Posts"

table.table.table-bordered
  thead
    tr
      th  Post's Author
      th  Post's Title
      th  Post's Description
  tbody
    - @posts.each do |post|
      tr
        th = link_to post.user.name, user_path(post.user)
        td = link_to post.title, post_path(post)
        td = post.description

app/views/posts/new.html.slim
= simple_form_for [@user, @post] do |f|
  = f.input :title, label: 'Post title'
  = f.input :description, label: 'Post content'
  = f.button :submit

app/views/posts/show.html.slim
= link_to "Create new post", new_user_posts_path(@post.user)

table
  thead
    tr
      th  Post's Title
      th  Post's Description
      th  Post's Comments
  tbody
    tr
      td = @post.title
      td = @post.description
      td = link_to "Comments", post_comments_path(@post)

app/views/users/index.html.slim
h1= "All Users"

= link_to "Create new user", new_user_path

table.table.table-bordered
  thead
    tr
      th  User Name
      th  User Description
  tbody
    - @users.each do |user|
      tr
        td = link_to user.name, user_path(user)
        td = user.description

app/views/users/new.html.slim
= simple_form_for @user do |f|
  = f.input :name, label: 'Your name'
  = f.input :description, label: 'Describe yourself'
  = f.button :submit

app/views/users/show.html.slim
table
  thead
    tr
      th  User Name
      th  User Description
      th  Posts
  tbody
    tr
      td = @user.name
      td = @user.description
      td = link_to "Posts", posts_path